### PR TITLE
move hawtjni args to a default profile

### PR DESCRIPTION
**Pull request by p8a**

### CODE REVIEW

**Comment by m91snik** [comment]
@p8a , could you release new yaralib version which includes this PR changes? It will really help me to move forward with my current tasks

**Comment by p8a** [comment]
@m91snik the code was already merged, are you having problems building ?

**Comment by m91snik** [comment]
@p8a , right, it's merged into master and I can build it locally with 3.5.0-SNAPSHOT version, but this is local build and snapshot one!
So, what I'm asking is to do release 3.5.0 (not snapshot) to maven repository to make it possible to add libyara as dependency to my maven project. Is it possible?

**Comment by p8a** [comment]
@m91snik unfortunately I cannot do that in such a short time.

**Pull request merged**
